version: "3.1"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--data-checksums"
